name: Build and upload to PyPI

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:

      - name: Log reason (manual run only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Reason for triggering: ${{ github.event.inputs.reason }}"

      - name: Checkout
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - name: Setup
      - uses: actions/setup-python@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_ARCHS_MACOS: x86_64
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_SKIP: "pp* *-win32 *-manylinux_i686"

      - name: Artifacts
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          if-no-files-found: error

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') ) || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
